# Generated by Django 5.0.1 on 2024-03-10 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cashout',
            old_name='cash_id',
            new_name='cash_in',
        ),
    ]
