# Generated by Django 5.0.1 on 2024-03-16 21:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0002_rename_cash_id_cashout_cash_in'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cashin',
            old_name='interrest',
            new_name='interrest_config',
        ),
    ]
