# Generated by Django 5.0.1 on 2024-03-18 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0003_rename_interrest_cashin_interrest_config'),
    ]

    operations = [
        migrations.AddField(
            model_name='cashin',
            name='interest',
            field=models.JSONField(default={}),
        ),
    ]
