# Generated by Django 5.0.1 on 2024-03-18 21:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0004_cashin_interest'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cashin',
            old_name='interest',
            new_name='interrest',
        ),
    ]
