# Generated by Django 5.0.1 on 2024-05-05 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0006_alter_cashin_interrest'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cashin',
            old_name='interrest',
            new_name='distribution',
        ),
    ]
