# Generated by Django 5.0.1 on 2024-01-14 20:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Agency', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='agency',
            name='created_by',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, related_name='agaency_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Create by'),
        ),
        migrations.AddField(
            model_name='firm',
            name='created_by',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, related_name='firm_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Create by'),
        ),
        migrations.AddField(
            model_name='agency',
            name='firm',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, related_name='firm_attachement', to='Agency.firm', verbose_name='Firm'),
        ),
        migrations.AddField(
            model_name='interrestrateconfig',
            name='created_by',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, related_name='rated_by', to=settings.AUTH_USER_MODEL, verbose_name='Config by'),
        ),
        migrations.AddField(
            model_name='liasonagency',
            name='created_by',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, related_name='liason_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created by'),
        ),
        migrations.AddField(
            model_name='liasonagency',
            name='destination',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, related_name='destination', to='Agency.agency', verbose_name='Destination agency'),
        ),
        migrations.AddField(
            model_name='liasonagency',
            name='origin',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, related_name='origin', to='Agency.agency', verbose_name='Origin agency'),
        ),
        migrations.AddField(
            model_name='interrestrateconfig',
            name='agency_liason',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, related_name='agency_relation', to='Agency.liasonagency', verbose_name='Agency relation'),
        ),
    ]
