# Generated by Django 5.0.1 on 2024-01-17 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Agency', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agency',
            name='detail',
            field=models.CharField(max_length=350, verbose_name='detail'),
        ),
        migrations.AlterField(
            model_name='agency',
            name='name',
            field=models.CharField(max_length=350, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='firm',
            name='address',
            field=models.CharField(max_length=350, verbose_name='Address'),
        ),
        migrations.AlterField(
            model_name='firm',
            name='email',
            field=models.CharField(max_length=350, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='firm',
            name='name',
            field=models.CharField(max_length=350, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='firm',
            name='phone',
            field=models.CharField(max_length=350, verbose_name='Phone'),
        ),
    ]
