# Generated by Django 5.0.1 on 2024-01-30 18:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Agency', '0003_alter_agency_detail_alter_agency_name_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='agency',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='agaency_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Create by'),
        ),
        migrations.AlterField(
            model_name='firm',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='firm_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Create by'),
        ),
        migrations.AlterField(
            model_name='liasonagency',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='liason_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created by'),
        ),
    ]
