# Generated by Django 5.0.1 on 2024-01-30 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Agency', '0005_alter_interrestrateconfig_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agency',
            name='detail',
            field=models.CharField(blank=True, max_length=350, null=True, verbose_name='detail'),
        ),
    ]
