# Generated by Django 5.0.1 on 2024-02-01 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Agency', '0006_alter_agency_detail'),
    ]

    operations = [
        migrations.AddField(
            model_name='interrestrateconfig',
            name='forfait',
            field=models.FloatField(default=0.0, verbose_name='rate'),
        ),
    ]
