# Generated by Django 5.0.1 on 2024-02-02 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Agency', '0007_interrestrateconfig_forfait'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interrestrateconfig',
            name='forfait',
            field=models.FloatField(default=0.0, verbose_name='Forfait'),
        ),
    ]
