# Generated by Django 5.0.1 on 2024-02-02 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Agency', '0008_alter_interrestrateconfig_forfait'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='agency',
            options={'verbose_name': 'Agency', 'verbose_name_plural': 'Agencies'},
        ),
        migrations.AlterModelOptions(
            name='interrestrateconfig',
            options={'verbose_name_plural': 'Interest configurations'},
        ),
        migrations.AlterModelOptions(
            name='liasonagency',
            options={'verbose_name_plural': 'Agencies liaison'},
        ),
        migrations.AddField(
            model_name='interrestrateconfig',
            name='threshold',
            field=models.FloatField(default=0.0, verbose_name='threshold | seuil'),
        ),
    ]
