# Generated by Django 5.0.1 on 2024-02-02 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Agency', '0009_alter_agency_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interrestrateconfig',
            name='rate',
            field=models.FloatField(default=0.0, verbose_name="rate | Taux d'interêt"),
        ),
    ]
